
spring:
  application:
    name: LoseFat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.137.157.119:3306/lose_fat?serverTimeZone=GMT%2b8
    url: jdbc:mysql://localhost:3306/lose_fat?serverTimeZone=GMT%2b8
    username: root
    password: 123456
#    password: 1007dzzxzz
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #修改mvc的匹配策略（Spring Boot 2.6.x版本引入依赖 springfox-boot-starter (Swagger 3.0) 后，启动容器会报错）
  servlet:
    multipart:
      max-file-size: 10MB # ???????????10MB
      max-request-size: 50MB  # ?????????50MB
  data:
    redis:
      host: 127.0.0.1
      port: 6379
server:
  port: 3000
  address: 0.0.0.0


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    map-underscore-to-camel-case: false # ??????
  mapper-locations: classpath*:mapper/*.xml

files: #????????
  upload:
    path: D:\IdeaProjects\LoseFat\files\
#    upload: 127.0.0.1:3000
#    path: /home/files/
#    upload: 192.168.213.153:3000

aliyun:
  AccessKeyId: LTAI5t8imLQeF1xq24fywm9j
  AccessKeySecret: vlvqBuVjrqFDIYHtdZIvr6IzOnVxxn