spring:
  application:
    name: loseFatBackstage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://8.137.157.119:3306/lose_fat?serverTimeZone=GMT%2b8
    url: jdbc:mysql://localhost:3306/lose_fat?serverTimeZone=GMT%2b8
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #??mvc??????Spring Boot 2.6.x?????? springfox-boot-starter (Swagger 3.0) ??????????
  data:
    redis:
      host: 127.0.0.1
      port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml